### ISSUE TITLE
Cant start ApromoreDocker

### ISSUE THREAD

**Issue by clauslor** [apromore/ApromoreDocker#8]
Hello,
I have just downloaded ApromoreDocker 0.1 release but could not start ApromoreDocker. Below is the error message I get. Can you please help?

>  ApromoreDocker-0.1$ ./start
>  ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the services key, or omit the version key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
`

>  java -version

> java version "1.8.0_201"
> Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
> Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

>  docker --version
> Docker version 18.09.1, build 4c52b90

> docker system info
> 
> Containers: 22
>  Running: 0
>  Paused: 0
>  Stopped: 22
> Images: 51
> Server Version: 18.09.1
> Storage Driver: overlay2
>  Backing Filesystem: extfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
> runc version: 96ec2177ae841256168fcf76954f7177af9446eb
> init version: fec3683
> Security Options:
>  apparmor
>  seccomp
>   Profile: default
> Kernel Version: 4.15.0-45-generic
> Operating System: Ubuntu 18.04.1 LTS
> OSType: linux
> Architecture: x86_64
> CPUs: 2
> Total Memory: 5.651GiB
> Name: osboxes
> ID: 2FVZ:MOAG:3UCS:LW2B:BXHQ:336X:I6M3:BW5A:OZGI:4Q5H:XSW4:5G5P
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false
> Product License: Community Engine
>

**Comment by verenich** [comment]
Hi,

Make sure you are using the latest Docker and Compose version
